# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0  # pause dependabot
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/src/assets/js'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0  # pause dependabot
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0  # pause dependabot
    commit-message:
      prefix: 'chore: '
    ignore:
      # Staying on phpunit 9.6.19 in order to keep supporting PHP 7.
      - dependency-name: 'phpunit/phpunit'

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'

  - package-ecosystem: 'composer'
    directory: '/src'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0  # pause dependabot
    commit-message:
      prefix: 'chore: '

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'
